---
title: "KNN"
author: "Ismael"
date: "19/02/2020"
output: html_document
---
# KNN algorithm in R
Libraries 
```{r}
library("gmodels")
library("class")
```
Loading the dataset
```{r}
wbcd <- read.csv("wisc_bc_data.csv", stringsAsFactors = FALSE)
str(wbcd)
```

We don't need the ID column since it's not important.
```{r}
wbcd <- wbcd[,-1]

```
Make the column diagnosis from wbcd as factor
```{r}
wbcd[,1] <- factor(wbcd$diagnosis, levels = c("B", "M"), labels = c("Benign", "Malign"))
```
Normalize the numeric columns and obtain  the training and test datasets and their labels
```{r}
wbcd_z <- as.data.frame(scale(wbcd[,-1]))
wbcd_train <- wbcd_z[1:469,]
wbcd_test <- wbcd_z[470:569,]
train_labels <- wbcd[1:469,1]
test_labels <- wbcd[470:569,1]
```

Applying the KNN algorithm
```{r}

wbcd_res <- knn(train = wbcd_train, test = wbcd_test, cl = train_labels , k = 22 )
```

Veifying if the result matches with the dataset
```{r}
CrossTable(x = test_labels, y = wbcd_res, prop.chisq = FALSE)
```

